---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Avg.
--- DateTime: 1/13/2022 3:32 PM
---

SDKDemo = require("SDKDemo")

local function main()
    --CS.UnityEngine.Debug.Log("hello demo!");
    print("hello demo!")
end

main()