---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Avg.
--- DateTime: 1/13/2022 5:44 PM
---

local demo = {}
local _demo_ui



local _test_cases = {}


_test_cases["first case"] = function()
    print("this is first case")
    CS.SDKWrapper.callSdkApi("com.unity3d.player.SDKWrapper", "Initialize", '{"code": 123}')
end



function demo.Init(demo_ui)
    print("SDKDemo.Init")
    CS.SDKWrapper.OnUnity3dSendMessage('+', function(json) print(json)  end)

    _demo_ui = demo_ui

    if not _demo_ui then
        return
    end

    for k, v in pairs(_test_cases) do
         _demo_ui:AddTestAction(k, v)
    end
    
end


return demo